name: check

on:
  push:

jobs:
  check:
    runs-on:
      - ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        pg_version: [17]
        compiler: [gcc]
        check_type: [valgrind_1]
    env:
      LLVM_VER: 18
      CPU: ${{ matrix.cpu }}
      CHECK_TYPE: ${{ matrix.check_type }}
      COMPILER: ${{ matrix.compiler }}
    steps:
      - name: Checkout extension code into workspace directory
        uses: actions/checkout@v4
        with:
          path: orioledb
      - name: Get the required tag name
        shell: bash
        run: |
          echo "PGTAG=$(grep '^${{ matrix.pg_version }}: ' orioledb/.pgtags | cut -d' ' -f2-)" >> $GITHUB_ENV

      - name: Restore cached pg
        id: cache
        uses: actions/cache/restore@v4
        with:
          path: ./pgsql
          key: ${{ runner.os }}-pg

      - name: Checkout PostgreSQL code into workspace directory
        uses: actions/checkout@v4
        with:
          repository: orioledb/postgres
          ref: ${{ env.PGTAG }}
          path: postgresql
      - name: Setup prerequisites
        run: bash ./orioledb/ci/prerequisites.sh
      - name: Build
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
        run: bash ./orioledb/ci/build.sh

      - name: Save cached pg
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ./pgsql
          key: ${{ runner.os }}-pg

      - name: Install post build prerequisites
        run: bash ./orioledb/ci/post_build_prerequisites.sh
      - name: Check
        timeout-minutes: ${{ startsWith(matrix.check_type, 'valgrind_') && 150 || 20 }}
        run: bash ./orioledb/ci/check.sh
      - name: Check output
        run: bash ./orioledb/ci/check_output.sh
        if: ${{ success() || failure() }}
      - name: Show stuck processes
        run: bash ./orioledb/ci/list_stuck.sh
        if: ${{ always() }}
